### ISSUE TITLE
Needs an update to be compatible with 0.6.0

### ISSUE THREAD

**Issue by ndelangen** [sourcejs/sourcejs-spec-dependencies#1] opened 2016-03-06 19:42 UTC
This is actually a very cool addition to sourcejs! I'd love to see it updated to work with sourcejs 0.6.0.

Any instructions on how to do this? If I know how to sourceJS changed between the time this was developed an 0.6.0, I might help getting this and some other packages up to speed.

As an additional idea: perhaps this package could list dependencies from `require()`s and `import`s from js / jsx files in the spec?

**Comment by ndelangen** [comment] 2016-03-06 22:25
After experimenting a bit and tweaking the /assets/index,js file a bit It's running without errors, but it's not generating any data in dependency_tree file, and not showing anything on spec pages about dependencies.

It does seem to have added a loading spinner when navigating to a spec page?

**Comment by robhrt7** [comment] 2016-03-09 16:39
Hi,

I'll check what's happened with it. Generally, we don't have really big breaking changes from version to version, so it should be easy to fix.

After I'll do it, I can guide you through the changes I've made, so if you like, you can help with other plugins.

**Comment by robhrt7** [comment] 2016-03-10 19:17
I've retested the current situation, it works with latest stable v.0.5.6, but not with SourceJS as NPM dependency. The problem is with how we look for user folder in new set-up.

Left a note in docs + added some missing things about configuration. After finishing `0.6.0` will plan plugin updates.

If you want to help, you can improve the file traversing mechanism in this plugin to use something common like `global.app.get('user')`.

**Comment by ndelangen** [comment] 2016-05-03 12:40
Does the [0.2.0](https://github.com/sourcejs/sourcejs-spec-dependencies/releases/tag/0.2.0) release fix this plugin with SourceJS as NPM dependency?

**Comment by robhrt7** [comment] 2016-05-03 13:22
Yes, 0.2.0 is specifically done for SourceJS 0.6.0, older versions are not supported since 0.2.x branch.

Seems like I can close the issue now, since SourceJS 0.6.0 is now supported.

**Closed as completed** 2016-05-03 13:23 UTC
